sudo: false

language: objective-c

before_install:
  - gem install xcpretty

script:
  - xcodebuild -workspace Ono.xcworkspace -scheme "Ono macOS" -sdk macosx | xcpretty
  - xcodebuild test -workspace Ono.xcworkspace -scheme "Ono macOS" -sdk macosx | xcpretty
